version: '3.3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - nodemernapp
    ports:
      - "80:3000"
    image: nodeapp 
    environment:
      - MONGO_URI=mongodb://mongo_db/nodeapp
  db:
    image: mongo:3.0.15
    networks:
      nodemernapp:
        aliases:
          - "mongo_db"
    volumes:
      - mongo-db:/data/db
networks:
  nodemernapp:
    driver: bridge
volumes: 
  mongo-db: